name: Clean untagged docker images

permissions:
  contents: read

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  clean:
    permissions:
      contents: write
    name: Clean untagged docker images
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run script
        run: ./delete_ghcr_dangling_images.sh lowlighter metrics
        working-directory: .github/actions/ghcr-clean
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_BOT_TOKEN }}
