name: Sync next with main
permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            with:
              fetch-depth: 0
              ref: staging

          - name: Set up Git config
            run: |
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --global merge.ours.driver true
              git remote add upstream https://github.com/terrapkg/packages

          - name: Merge main into staging
            env:
              GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
            run: |
              git fetch origin main
              git merge --no-edit origin/main
              git push origin staging
